---
title: "Simulating Misclassification Error and Bias in Transgender Health Studies using Electronic Health Records and Administrative Claims Databases"
author: "Elle Lett"
header-includes:
   - \usepackage{amsmath}
output: 
  html_document:
    toc: false 
    depth: 3 
    theme: paper 
    highlight: tango
---
```{r set-options, echo=FALSE, cache=FALSE,message=FALSE,warning=FALSE}
options(width = 400)
library(knitr)
library(Hmisc)
```  

### Overview



**Background**: Electronic health records (EHRs) and administrative claims databases are increasingly being used to study the distribution of health outcomes among transgender individuals. However, gender identity is not comprehensively reported in these data sources so diagnosis codes are used as a proxy to identify transgender subgroups within the data. To date, no study has characterized the bias introduced by misclassification of gender identity based on this proxy metric.

**Objective**:  The goal of this study is to estimate the bias introduced by misclassification of gender identity in estimates of health inequities among transgender individuals and multiply marginalized racial/ethnic subgroups. 

**Data**: We use simulations to generate data subject to differential misclassification error related to gender identity and racial identity, and estimate the bias, mean squared error, and coverage probability for the observed odds ratios comparing the various groups.

**Faculty Input**: I spoke with John Holmes who provided some input on how to visiualize the results, and Drs. Jaya Asyola and Nadia Dowshen who gave input on what information to use parametrize the simulations. 

### Introduction 

  There is an extensive body of literature that documents the severe health inequities experienced by transgender individuals, or persons who identify with a gender that is different than the sex they were assigned at birth. These inequities include mental health disorders, such as suicidality, anxiety, depression, and ADHD, negative experiences of discrimination and victimization including healthcare discrimination, sexual violence, and psychosocial and behavioral health-related factors including behaviors associated with HIV and other STIs. The data underlying these studies are sourced from several settings: 1) small, site or regional cohorts,  2) national surveys that ascertained transgender identity and 3) electronic health records or large claims databases. The first data source has the benefit of being derived from studies that are designed to center the specific needs of transgender individuals and are more likely to assess outcomes relevant to this population with the appropriate granularity. However, these studies rarely include cisgender comparison groups excluding the possibility of obtaining within study estimates comparing the distribution of outcomes between cisgender and transgender groups to approximate the effect of transphobia on health outcomes.  The latter two data sources often contain both cisgender and transgender groups, thereby allowing association measures to be assessed across groups, or identification of causal estimates when appropriate measures of structural oppression are included. The third category is unique in that you can obtain granular data on specific health outcomes on nationally representative samples. 

  All studies that have used EHR and claims databases to assess transgender health have used International Classification of Disease (ICD) diagnosis codes for gender dysphoria, occasionally augmented by other relevant diagnosis codes such as “endocrine disorder otherwise not specified” that are enriched in encounters with transgender individuals seeking care. These measures, particularly those for gender dysphoria are highly specific. It is unlikely that an individual who is not transgender would carry these diagnoses in their claims or EHR. However, it is unclear to what degree these algorithms are sensitive, and in fact it is reasonable to assume that they are not. Not all transgender individuals who are seeking medical care will be doing so specifically for gender affirmation, so they are less likely to carry the codes used in the algorithm for identifying transgender individuals. Therefore, these algorithms introduce differential misclassification error between cisgender and transgender individuals which has the potential to bias estimates of health inequities for transgender populations.  To accurately interpret findings from transgender population health studies using EHR and claims, it is necessary to characterize the effect of differential misclassification error introduced by current algorithms used for identifying transgender individuals. 

  This study is interdisciplinary because it encompasses health services research and informatics by addressing a knowledge gap in using EHR and administrative claims data, engages statistics by simulating data and quantifying bias, and social epidemiology by focusing on population health for groups at the intersection of multiple marginalized identities. 

### Methods

***Simulation Rationale***

In our study we will simulate the effect of misclassification on the bias of estimated odds ratios (OR) measuring the association of a binary outcome with gender identity comparing cisgender individuals to transgender individuals, where, with some probability, transgender individuals are misclassified as cisgender. We will also consider scenarios in which the outcome are also associated with misclassification of transgender individuals. These scenarios are reasonable if an outcome decreases the likelihood that an individual will be seeking gender-related care such that, in the presence of this outcome, transgender individuals are not likely to carry ICD codes for gender dysphoria or related conditions, because they are being treated for other conditions. These scenarios will allow us to estimate the bias due to misclassification error of transgender individuals in the context of estimating inequities across transgender and cisgender populations.

***Data Generation Mechanism and Analysis***

1. Simulate n=100,000 individuals

\begin{equation}
\pi_{G}=P[G_i=1]=0.10 \\
G_i\sim\mathbf{Bernoulli}(\pi_{G})\\
\pi_{y,i}=expit[\beta_0+\beta_1G_i]\\
\mathrm{OR}=e^{\beta_1}\\
Y_i\sim\mathbf{Bernoulli}(\pi_{Y,i})\\
\pi_{M,i}=G_i*expit[\alpha_0++\alpha_2Y_i]\\
M_i\sim\mathbf{Bernoulli}(\pi_{M,i})\\
G^*_i=M_i(1-G_i)+(1-M_i)G_i\\
\end{equation}

2. Fit the outcome model based on the simulated data and observed gender.

\begin{equation}

\end{equation}


Figure 1 outlines the data generation mechanism for the simulations, and shows the models used at each step. In the first step, for individual i, gender and race are randomly selected from a Bernoulli distribution with a pre-specified probability. These variables, Gi and Bi, are 1 if the individual i is transgender or Black, respectively.  In the next step, conditional on gender and race, a binary outcome, Yi, is randomly drawn, based on a Bernoulli probability from a logit linear model that includes an interaction between gender and race, to account for modification between race and gender for the outcome. In the third step, a binary indicator for misclassification, Mi, conditional on gender, race, and the outcome, is drawn. In EHR- and claims- data based studies of transgender populations, all individuals are presumed to be cisgender unless they carry gender dysphoria diagnosis codes. Because these codes are specific to transgender individuals and cisgender individuals are unlikely to carry them, we assume that misclassification errors are one-way, such that transgender individuals may be misclassified as cisgender, but the converse is not true. Therefore, our simulations assume that all cisgender individuals are accurately classified (Mi=0), and transgender individuals are misclassified (Mi=1) with Bernoulli probability conditional on their race and outcome status. Then, the observed gender, Gi*, is generated where Gi*=Gi for individuals who are classified correctly (Mi=0), and Gi*=1-Gi, for individuals who are misclassified. This process is repeated for n=100000 individuals, and the last step is to estimate the odds ratios of interest using a logit model that includes observed gender (Gi*), race (Bi), and their interaction. This process is repeated N=1,000 times to estimate the empirical distribution based of the estimated odds ratios based on a given simulation scenario. For each simulation scenario and each of the three odds ratios of interest, we report the mean bias, variance, mean squared error, and the coverage probability of confidence intervals using standard errors based on delta method.23 We also show the distribution of all estimated ORs across all scenarios on violin plots, a data display analogous to box plots but with the addition of representing the distribution of estimates with by contracting or expanding the plotting area based on the density of estimates in that region.24

***Simulation Parameter Specification***
cording to a study conducted by the Williams Institute using data from the Behavioral Risk Factor Surveillance System, approximately 0.6% of the adult US population is transgender However, this is likely an underestimate because the BRFSS survey instrument uses a one-question format to identify transgender individuals which has been shown to underestimate the transgender population size by half.2Therefore, in our simulation studies, we will set the prevalence of the transgender population to 1%. In studies using claims data, the percentage of individuals meeting the diagnosis code-based criteria has been reported to be as low as 0.026% which suggests potentially very severe misclassification, given the order of magnitude difference between the observed transgender population in these national databases, and the estimated population frequency of transgender individuals.13  Therefore, we test a broad range of misclassification probabilities with transgender White individuals negative for the simulated health outcome ranging from 10% to 50% probability, increasing to transgender Black individuals positive for the simulated health outcome ranging from 30% to 91%. Lastly, we simulate bias under a wide range of estimated effect sizes (ORs from 1.51 to 6.75) because prior studies have estimated effect sizes in transgender health inequities as high as 8.5, comparing the odds of mental health diagnoses across gender identities.13 Figure 1 provides additional details on model parameters of the data generation mechanism that attain these simulated values for association measures and misclassification probabilities. 

***Analysis***

For the analysis, we will calculate the following measures for the performance of our estimator .Below, $\hat{\theta}$ refers to the simulated values (estimates) of the odds ratio, $\theta$ refers to the true value of the odds ratio, $E$ refers to the expectation operation. Also, bars above indicate means, and hats indicate estimates. 

Bias is a measure of how far an estimator is from the true value, and the formula is given below. 
$$
Bias(\hat{\theta})=\mathrm{E}[\hat{\theta_i}-\theta]\\
$$
The estimated bias, based on N estimates of $\theta$ is: 

$$
\hat{Bias(\hat{\theta})}=\frac{\sum{[\hat{\theta_i}-\theta}]}{N}
$$

Variance is a measure of the spread of the estimates, and is given below.

$$
Var(\hat{\theta})=\mathrm{E}\bigg[(\hat{\theta_i}-\mathrm{E}[\theta_i])^2\bigg]
$$
The estiamted varias, based on estimates of $\theta$, $\theta_i$ is:

$$
\hat{Var(\hat{\theta})}=\frac{\sum_i({\hat{\theta_i}-\bar{\hat{\theta}_i}})^2}{N-1}
$$

$$
MSE(\hat{\theta})=\mathrm{E}\bigg[(\hat{\theta_i}-\theta)^2\bigg]\\
$$
$$
\hat{MSE(\hat{\theta})}=\frac{\sum_i({\hat{\theta_i}-\theta})^2}{N-1}
$$




### Results


Table 1 shows the summary statistics for all scenarios and odds ratios. For all ORs, the estimates are unbiased when the there is no misclassification (percent bias between -0.07% to 0.18%). For OR1, comparing White transgender to White cisgender groups, the bias in the estimates increases with the strength of transgender misclassification, specifically a downward bias of 5.58% downward under mild misclassification to 22.39% downward bias under severe misclassification with a mild effect (True OR: 1.51). Similar results for bias were found with for moderate effect (True OR: 2.01) and strong effect (True OR: 3.00). However, the decrease in coverage probability differed by strength of effect and strength of misclassification.  With the mild effect, the coverage probability decreased from 0.96 with no misclassification, to 0.646, 0.03, and 0.002 with mild, moderate, and severe misclassification, respectfully. With stronger effect sizes, the rate of decline in coverage probability was steeper, with a drop to 0.56 in mild misclassification for moderate effect size, and 0.456 with strong effect size. The distribution of OR estimates for all effect and misclassification strengths, across all scenarios is shown in the violin plot for Figure 2. 
Results for OR2, comparing transgender Blacks to cisgender Whites were similar to OR1. Across all effect sizes for OR2, bias increased with increasing misclassification, from around -16% at mild misclassification to around -33% with severe misclassification. Similar with OR1 coverage probability declines with increasing misclassification, except, between moderate and severe misclassification, across all effect strengths, where for mild effect the coverage improves from 0.237 to 0.392, and strong effect it improves from 0.09 to 0.197. This occurs concurrently with increases in variance and mean squared error (Table 1). 

For OR3, comparing transgender Blacks to transgender Whites, bias increases from mild to moderate misclassification strengths from around -11% to around -16% across all effect strengths. However, the bias declined from moderate to severe to around -13%. Across all effect sizes, the variance and MSE increases with increased misclassification error. 



### Conclusion

Studies using EHR and administrative claims data to estimate transgender health inequities are growing in popularity. These studies have the potential to set policy agendas on the institutional level because of their large size when using local EHRs and on the national level when using large claims databases, because of their regional diversity. Therefore, these studies are high priority and should continue to expand the scientific record and provide more comprehensive data on transgender health as we work toward achieving health equity. However, our results indicate that comparisons between transgender and cisgender groups using proxy measures subject to misclassification are biased and must be interpreted carefully.13,14,28 Specifically, such studies are most suited for identifying strong associations but may lead to false negatives with moderate or mild associations. Further, the associations that are captured are underestimated under misclassification, so results from such studies must be interpreted with that limitation. Lastly, when centering racial/ethnic minority subpopulations within the transgender community, estimated associations have decreased precision due to the combination of gender identity misclassification and small substrata sample size.

Given the condition of misclassification, EHR- and claims- data based studies should be viewed as screening tools for only the most disparate health outcomes between transgender and cisgender populations, and researchers should not deprioritize health outcomes with null findings based on these data alone. Similarly, studies that are not concerned with comparisons but use diagnosis codes to generate cohorts of transgender individuals to estimate prevalence are subject to selection bias such that their results are not generalizable to the transgender population at large. 12,29–31 The impact of this selection bias is hard to predict but given the decreased healthcare access,3,4 and socioeconomic resources faced by transgender groups, it is likely that the most vulnerable subgroups within the transgender community are differentially misclassified as cisgender, which would also bias results toward the null. 

The ideal solution to the misclassification problem is clear; for EHR data, healthcare systems should routinely ascertain patient-reported gender identity and these demographics should be included, as suggested by the 2011 recommendations from the Institute of Medicine (IOM)32 and the Joint Commission, 33 and required for all health care systems certified under the federal Stage 3 Meaningful Use Guidelines.34  Despite these recommendations, uptake of sexual orientation and gender identity (SOGI) data in the EHR has been poor, with a recent study of over 1300 US health systems indicating missing SOGI data for 63% of patients.35  Several reports have offered guidelines to address challenges on SOGI data collection implementation with recommendations for staff training and electronic record customization.36,37 Additionally, large claims databases such as IBM Marketscan38 and Optum Labs39 should include fields for SOGI data for health services researchers, to allow for precise, unbiased estimates of transgender health inequities using these data sources.  
